/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChatBot {
    }
}
declare global {
    interface HTMLChatBotElement extends Components.ChatBot, HTMLStencilElement {
    }
    var HTMLChatBotElement: {
        prototype: HTMLChatBotElement;
        new (): HTMLChatBotElement;
    };
    interface HTMLElementTagNameMap {
        "chat-bot": HTMLChatBotElement;
    }
}
declare namespace LocalJSX {
    interface ChatBot {
    }
    interface IntrinsicElements {
        "chat-bot": ChatBot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chat-bot": LocalJSX.ChatBot & JSXBase.HTMLAttributes<HTMLChatBotElement>;
        }
    }
}
